<?php

namespace Database\Seeders;

use App\Models\region;
use DB;
use Illuminate\Database\Seeder;


class RegionSeeder extends Seeder
{
    public function run()
    {

        DB::table('regions')->insert([
            ['id' => 1,'descripcion'=>'Arica y Parinacota','ordinal'=>'XV'],
            ['id' => 2,'descripcion'=>'Tarapacá','ordinal'=>'I'],
            ['id' => 3,'descripcion'=>'Antofagasta','ordinal'=>'II'],
            ['id' => 4,'descripcion'=>'Atacama','ordinal'=>'III'],
            ['id' => 5,'descripcion'=>'Coquimbo','ordinal'=>'IV'],
            ['id' => 6,'descripcion'=>'Valparaiso','ordinal'=>'V'],
            ['id' => 7,'descripcion'=>'Metropolitana de Santiago','ordinal'=>'RM'],
            ['id' => 8,'descripcion'=>'Libertador General Bernardo O\'Higgins','ordinal'=>'VI'],
            ['id' => 9,'descripcion'=>'Maule','ordinal'=>'VII'],
            ['id' => 10,'descripcion'=>'Biobío','ordinal'=>'VIII'],
            ['id' => 11,'descripcion'=>'La Araucanía','ordinal'=>'IX'],
            ['id' => 12,'descripcion'=>'Los Ríos','ordinal'=>'XIV'],
            ['id' => 13,'descripcion'=>'Los Lagos','ordinal'=>'X'],
            ['id' => 14,'descripcion'=>'Aisén del General Carlos Ibáñez del Campo','ordinal'=>'XI'],
            ['id' => 15,'descripcion'=>'Magallanes y de la Antártica Chilena','ordinal'=>'XII']
        ]);
        DB::table('provincias')->insert([
            ['id'=>1,'descripcion'=>'Arica','region_id'=>1],
            ['id'=>2,'descripcion'=>'Parinacota','region_id'=>1],
            ['id'=>3,'descripcion'=>'Iquique','region_id'=>2],
            ['id'=>4,'descripcion'=>'El Tamarugal','region_id'=>2],
            ['id'=>5,'descripcion'=>'Antofagasta','region_id'=>3],
            ['id'=>6,'descripcion'=>'El Loa','region_id'=>3],
            ['id'=>7,'descripcion'=>'Tocopilla','region_id'=>3],
            ['id'=>8,'descripcion'=>'Chañaral','region_id'=>4],
            ['id'=>9,'descripcion'=>'Copiapó','region_id'=>4],
            ['id'=>10,'descripcion'=>'Huasco','region_id'=>4],
            ['id'=>11,'descripcion'=>'Choapa','region_id'=>5],
            ['id'=>12,'descripcion'=>'Elqui','region_id'=>5],
            ['id'=>13,'descripcion'=>'Limarí','region_id'=>5],
            ['id'=>14,'descripcion'=>'Isla de Pascua','region_id'=>6],
            ['id'=>15,'descripcion'=>'Los Andes','region_id'=>6],
            ['id'=>16,'descripcion'=>'Petorca','region_id'=>6],
            ['id'=>17,'descripcion'=>'Quillota','region_id'=>6],
            ['id'=>18,'descripcion'=>'San Antonio','region_id'=>6],
            ['id'=>19,'descripcion'=>'San Felipe de Aconcagua','region_id'=>6],
            ['id'=>20,'descripcion'=>'Valparaiso','region_id'=>6],
            ['id'=>21,'descripcion'=>'Chacabuco','region_id'=>7],
            ['id'=>22,'descripcion'=>'Cordillera','region_id'=>7],
            ['id'=>23,'descripcion'=>'Maipo','region_id'=>7],
            ['id'=>24,'descripcion'=>'Melipilla','region_id'=>7],
            ['id'=>25,'descripcion'=>'Santiago','region_id'=>7],
            ['id'=>26,'descripcion'=>'Talagante','region_id'=>7],
            ['id'=>27,'descripcion'=>'Cachapoal','region_id'=>8],
            ['id'=>28,'descripcion'=>'Cardenal Caro','region_id'=>8],
            ['id'=>29,'descripcion'=>'Colchagua','region_id'=>8],
            ['id'=>30,'descripcion'=>'Cauquenes','region_id'=>9],
            ['id'=>31,'descripcion'=>'Curicó','region_id'=>9],
            ['id'=>32,'descripcion'=>'Linares','region_id'=>9],
            ['id'=>33,'descripcion'=>'Talca','region_id'=>9],
            ['id'=>34,'descripcion'=>'Arauco','region_id'=>10],
            ['id'=>35,'descripcion'=>'Bio Bío','region_id'=>10],
            ['id'=>36,'descripcion'=>'Concepción','region_id'=>10],
            ['id'=>37,'descripcion'=>'Ñuble','region_id'=>10],
            ['id'=>38,'descripcion'=>'Cautín','region_id'=>11],
            ['id'=>39,'descripcion'=>'Malleco','region_id'=>11],
            ['id'=>40,'descripcion'=>'Valdivia','region_id'=>12],
            ['id'=>41,'descripcion'=>'Ranco','region_id'=>12],
            ['id'=>42,'descripcion'=>'Chiloé','region_id'=>13],
            ['id'=>43,'descripcion'=>'Llanquihue','region_id'=>13],
            ['id'=>44,'descripcion'=>'Osorno','region_id'=>13],
            ['id'=>45,'descripcion'=>'Palena','region_id'=>13],
            ['id'=>46,'descripcion'=>'Aisén','region_id'=>14],
            ['id'=>47,'descripcion'=>'Capitán Prat','region_id'=>14],
            ['id'=>48,'descripcion'=>'Coihaique','region_id'=>14],
            ['id'=>49,'descripcion'=>'General Carrera','region_id'=>14],
            ['id'=>50,'descripcion'=>'Antártica Chilena','region_id'=>15],
            ['id'=>51,'descripcion'=>'Magallanes','region_id'=>15],
            ['id'=>52,'descripcion'=>'Tierra del Fuego','region_id'=>15],
            ['id'=>53,'descripcion'=>'Última Esperanza','region_id'=>15]
        ]);
        DB::table('comunas')->insert([
            ['id'=>1,'descripcion'=>'Arica','provincia_id'=>1],
            ['id'=>2,'descripcion'=>'Camarones','provincia_id'=>1],
            ['id'=>3,'descripcion'=>'General Lagos','provincia_id'=>2],
            ['id'=>4,'descripcion'=>'Putre','provincia_id'=>2],
            ['id'=>5,'descripcion'=>'Alto Hospicio','provincia_id'=>3],
            ['id'=>6,'descripcion'=>'Iquique','provincia_id'=>3],
            ['id'=>7,'descripcion'=>'Camiña','provincia_id'=>4],
            ['id'=>8,'descripcion'=>'Colchane','provincia_id'=>4],
            ['id'=>9,'descripcion'=>'Huara','provincia_id'=>4],
            ['id'=>10,'descripcion'=>'Pica','provincia_id'=>4],
            ['id'=>11,'descripcion'=>'Pozo Almonte','provincia_id'=>4],
            ['id'=>12,'descripcion'=>'Antofagasta','provincia_id'=>5],
            ['id'=>13,'descripcion'=>'Mejillones','provincia_id'=>5],
            ['id'=>14,'descripcion'=>'Sierra Gorda','provincia_id'=>5],
            ['id'=>15,'descripcion'=>'Taltal','provincia_id'=>5],
            ['id'=>16,'descripcion'=>'Calama','provincia_id'=>6],
            ['id'=>17,'descripcion'=>'Ollague','provincia_id'=>6],
            ['id'=>18,'descripcion'=>'San Pedro de Atacama','provincia_id'=>6],
            ['id'=>19,'descripcion'=>'María Elena','provincia_id'=>7],
            ['id'=>20,'descripcion'=>'Tocopilla','provincia_id'=>7],
            ['id'=>21,'descripcion'=>'Chañaral','provincia_id'=>8],
            ['id'=>22,'descripcion'=>'Diego de Almagro','provincia_id'=>8],
            ['id'=>23,'descripcion'=>'Caldera','provincia_id'=>9],
            ['id'=>24,'descripcion'=>'Copiapó','provincia_id'=>9],
            ['id'=>25,'descripcion'=>'Tierra Amarilla','provincia_id'=>9],
            ['id'=>26,'descripcion'=>'Alto del Carmen','provincia_id'=>10],
            ['id'=>27,'descripcion'=>'Freirina','provincia_id'=>10],
            ['id'=>28,'descripcion'=>'Huasco','provincia_id'=>10],
            ['id'=>29,'descripcion'=>'Vallenar','provincia_id'=>10],
            ['id'=>30,'descripcion'=>'Canela','provincia_id'=>11],
            ['id'=>31,'descripcion'=>'Illapel','provincia_id'=>11],
            ['id'=>32,'descripcion'=>'Los Vilos','provincia_id'=>11],
            ['id'=>33,'descripcion'=>'Salamanca','provincia_id'=>11],
            ['id'=>34,'descripcion'=>'Andacollo','provincia_id'=>12],
            ['id'=>35,'descripcion'=>'Coquimbo','provincia_id'=>12],
            ['id'=>36,'descripcion'=>'La Higuera','provincia_id'=>12],
            ['id'=>37,'descripcion'=>'La Serena','provincia_id'=>12],
            ['id'=>38,'descripcion'=>'Paihuaco','provincia_id'=>12],
            ['id'=>39,'descripcion'=>'Vicuña','provincia_id'=>12],
            ['id'=>40,'descripcion'=>'Combarbalá','provincia_id'=>13],
            ['id'=>41,'descripcion'=>'Monte Patria','provincia_id'=>13],
            ['id'=>42,'descripcion'=>'Ovalle','provincia_id'=>13],
            ['id'=>43,'descripcion'=>'Punitaqui','provincia_id'=>13],
            ['id'=>44,'descripcion'=>'Río Hurtado','provincia_id'=>13],
            ['id'=>45,'descripcion'=>'Isla de Pascua','provincia_id'=>14],
            ['id'=>46,'descripcion'=>'Calle Larga','provincia_id'=>15],
            ['id'=>47,'descripcion'=>'Los Andes','provincia_id'=>15],
            ['id'=>48,'descripcion'=>'Rinconada','provincia_id'=>15],
            ['id'=>49,'descripcion'=>'San Esteban','provincia_id'=>15],
            ['id'=>50,'descripcion'=>'La Ligua','provincia_id'=>16],
            ['id'=>51,'descripcion'=>'Papudo','provincia_id'=>16],
            ['id'=>52,'descripcion'=>'Petorca','provincia_id'=>16],
            ['id'=>53,'descripcion'=>'Zapallar','provincia_id'=>16],
            ['id'=>54,'descripcion'=>'Hijuelas','provincia_id'=>17],
            ['id'=>55,'descripcion'=>'La Calera','provincia_id'=>17],
            ['id'=>56,'descripcion'=>'La Cruz','provincia_id'=>17],
            ['id'=>57,'descripcion'=>'Limache','provincia_id'=>17],
            ['id'=>58,'descripcion'=>'Nogales','provincia_id'=>17],
            ['id'=>59,'descripcion'=>'Olmué','provincia_id'=>17],
            ['id'=>60,'descripcion'=>'Quillota','provincia_id'=>17],
            ['id'=>61,'descripcion'=>'Algarrobo','provincia_id'=>18],
            ['id'=>62,'descripcion'=>'Cartagena','provincia_id'=>18],
            ['id'=>63,'descripcion'=>'El Quisco','provincia_id'=>18],
            ['id'=>64,'descripcion'=>'El Tabo','provincia_id'=>18],
            ['id'=>65,'descripcion'=>'San Antonio','provincia_id'=>18],
            ['id'=>66,'descripcion'=>'Santo Domingo','provincia_id'=>18],
            ['id'=>67,'descripcion'=>'Catemu','provincia_id'=>19],
            ['id'=>68,'descripcion'=>'Llaillay','provincia_id'=>19],
            ['id'=>69,'descripcion'=>'Panquehue','provincia_id'=>19],
            ['id'=>70,'descripcion'=>'Putaendo','provincia_id'=>19],
            ['id'=>71,'descripcion'=>'San Felipe','provincia_id'=>19],
            ['id'=>72,'descripcion'=>'Santa María','provincia_id'=>19],
            ['id'=>73,'descripcion'=>'Casablanca','provincia_id'=>20],
            ['id'=>74,'descripcion'=>'Concón','provincia_id'=>20],
            ['id'=>75,'descripcion'=>'Juan Fernández','provincia_id'=>20],
            ['id'=>76,'descripcion'=>'Puchuncaví','provincia_id'=>20],
            ['id'=>77,'descripcion'=>'Quilpué','provincia_id'=>20],
            ['id'=>78,'descripcion'=>'Quintero','provincia_id'=>20],
            ['id'=>79,'descripcion'=>'Valparaíso','provincia_id'=>20],
            ['id'=>80,'descripcion'=>'Villa Alemana','provincia_id'=>20],
            ['id'=>81,'descripcion'=>'Viña del Mar','provincia_id'=>20],
            ['id'=>82,'descripcion'=>'Colina','provincia_id'=>21],
            ['id'=>83,'descripcion'=>'Lampa','provincia_id'=>21],
            ['id'=>84,'descripcion'=>'Tiltil','provincia_id'=>21],
            ['id'=>85,'descripcion'=>'Pirque','provincia_id'=>22],
            ['id'=>86,'descripcion'=>'Puente Alto','provincia_id'=>22],
            ['id'=>87,'descripcion'=>'San José de Maipo','provincia_id'=>22],
            ['id'=>88,'descripcion'=>'Buin','provincia_id'=>23],
            ['id'=>89,'descripcion'=>'Calera de Tango','provincia_id'=>23],
            ['id'=>90,'descripcion'=>'Paine','provincia_id'=>23],
            ['id'=>91,'descripcion'=>'San Bernardo','provincia_id'=>23],
            ['id'=>92,'descripcion'=>'Alhué','provincia_id'=>24],
            ['id'=>93,'descripcion'=>'Curacaví','provincia_id'=>24],
            ['id'=>94,'descripcion'=>'María Pinto','provincia_id'=>24],
            ['id'=>95,'descripcion'=>'Melipilla','provincia_id'=>24],
            ['id'=>96,'descripcion'=>'San Pedro','provincia_id'=>24],
            ['id'=>97,'descripcion'=>'Cerrillos','provincia_id'=>25],
            ['id'=>98,'descripcion'=>'Cerro Navia','provincia_id'=>25],
            ['id'=>99,'descripcion'=>'Conchalí','provincia_id'=>25],
            ['id'=>100,'descripcion'=>'El Bosque','provincia_id'=>2],
            ['id'=>101,'descripcion'=>'Estación Central','provincia_id'=>25],
            ['id'=>102,'descripcion'=>'Huechuraba','provincia_id'=>2],
            ['id'=>103,'descripcion'=>'Independencia','provincia_id'=>25],
            ['id'=>104,'descripcion'=>'La Cisterna','provincia_id'=>25],
            ['id'=>105,'descripcion'=>'La Granja','provincia_id'=>25],
            ['id'=>106,'descripcion'=>'La Florida','provincia_id'=>25],
            ['id'=>107,'descripcion'=>'La Pintana','provincia_id'=>25],
            ['id'=>108,'descripcion'=>'La Reina','provincia_id'=>25],
            ['id'=>109,'descripcion'=>'Las Condes','provincia_id'=>25],
            ['id'=>110,'descripcion'=>'Lo Barnechea','provincia_id'=>25],
            ['id'=>111,'descripcion'=>'Lo Espejo','provincia_id'=>25],
            ['id'=>112,'descripcion'=>'Lo Prado','provincia_id'=>25],
            ['id'=>113,'descripcion'=>'Macul','provincia_id'=>25],
            ['id'=>114,'descripcion'=>'Maipú','provincia_id'=>25],
            ['id'=>115,'descripcion'=>'Ñuñoa','provincia_id'=>25],
            ['id'=>116,'descripcion'=>'Pedro Aguirre Cerda','provincia_id'=>25],
            ['id'=>117,'descripcion'=>'Peñalolén','provincia_id'=>25],
            ['id'=>118,'descripcion'=>'Providencia','provincia_id'=>25],
            ['id'=>119,'descripcion'=>'Pudahuel','provincia_id'=>25],
            ['id'=>120,'descripcion'=>'Quilicura','provincia_id'=>25],
            ['id'=>121,'descripcion'=>'Quinta Normal','provincia_id'=>25],
            ['id'=>122,'descripcion'=>'Recoleta','provincia_id'=>25],
            ['id'=>123,'descripcion'=>'Renca','provincia_id'=>25],
            ['id'=>124,'descripcion'=>'San Miguel','provincia_id'=>25],
            ['id'=>125,'descripcion'=>'San Joaquín','provincia_id'=>25],
            ['id'=>126,'descripcion'=>'San Ramón','provincia_id'=>25],
            ['id'=>127,'descripcion'=>'Santiago','provincia_id'=>25],
            ['id'=>128,'descripcion'=>'Vitacura','provincia_id'=>25],
            ['id'=>129,'descripcion'=>'El Monte','provincia_id'=>26],
            ['id'=>130,'descripcion'=>'Isla de Maipo','provincia_id'=>26],
            ['id'=>131,'descripcion'=>'Padre Hurtado','provincia_id'=>26],
            ['id'=>132,'descripcion'=>'Peñaflor','provincia_id'=>26],
            ['id'=>133,'descripcion'=>'Talagante','provincia_id'=>26],
            ['id'=>134,'descripcion'=>'Codegua','provincia_id'=>27],
            ['id'=>135,'descripcion'=>'Coínco','provincia_id'=>27],
            ['id'=>136,'descripcion'=>'Coltauco','provincia_id'=>27],
            ['id'=>137,'descripcion'=>'Doñihue','provincia_id'=>27],
            ['id'=>138,'descripcion'=>'Graneros','provincia_id'=>27],
            ['id'=>139,'descripcion'=>'Las Cabras','provincia_id'=>27],
            ['id'=>140,'descripcion'=>'Machalí','provincia_id'=>2],
            ['id'=>141,'descripcion'=>'Malloa','provincia_id'=>27],
            ['id'=>142,'descripcion'=>'Mostazal','provincia_id'=>27],
            ['id'=>143,'descripcion'=>'Olivar','provincia_id'=>27],
            ['id'=>144,'descripcion'=>'Peumo','provincia_id'=>27],
            ['id'=>145,'descripcion'=>'Pichidegua','provincia_id'=>27],
            ['id'=>146,'descripcion'=>'Quinta de Tilcoco','provincia_id'=>27],
            ['id'=>147,'descripcion'=>'Rancagua','provincia_id'=>27],
            ['id'=>148,'descripcion'=>'Rengo','provincia_id'=>27],
            ['id'=>149,'descripcion'=>'Requínoa','provincia_id'=>27],
            ['id'=>150,'descripcion'=>'San Vicente de Tagua Tagua','provincia_id'=>27],
            ['id'=>151,'descripcion'=>'La Estrella','provincia_id'=>28],
            ['id'=>152,'descripcion'=>'Litueche','provincia_id'=>28],
            ['id'=>153,'descripcion'=>'Marchihue','provincia_id'=>28],
            ['id'=>154,'descripcion'=>'Navidad','provincia_id'=>28],
            ['id'=>155,'descripcion'=>'Peredones','provincia_id'=>28],
            ['id'=>156,'descripcion'=>'Pichilemu','provincia_id'=>28],
            ['id'=>157,'descripcion'=>'Chépica','provincia_id'=>29],
            ['id'=>158,'descripcion'=>'Chimbarongo','provincia_id'=>29],
            ['id'=>159,'descripcion'=>'Lolol','provincia_id'=>29],
            ['id'=>160,'descripcion'=>'Nancagua','provincia_id'=>29],
            ['id'=>161,'descripcion'=>'Palmilla','provincia_id'=>29],
            ['id'=>162,'descripcion'=>'Peralillo','provincia_id'=>29],
            ['id'=>163,'descripcion'=>'Placilla','provincia_id'=>29],
            ['id'=>164,'descripcion'=>'Pumanque','provincia_id'=>29],
            ['id'=>165,'descripcion'=>'San Fernando','provincia_id'=>29],
            ['id'=>166,'descripcion'=>'Santa Cruz','provincia_id'=>29],
            ['id'=>167,'descripcion'=>'Cauquenes','provincia_id'=>30],
            ['id'=>168,'descripcion'=>'Chanco','provincia_id'=>30],
            ['id'=>169,'descripcion'=>'Pelluhue','provincia_id'=>30],
            ['id'=>170,'descripcion'=>'Curicó','provincia_id'=>31],
            ['id'=>171,'descripcion'=>'Hualañé','provincia_id'=>31],
            ['id'=>172,'descripcion'=>'Licantén','provincia_id'=>31],
            ['id'=>173,'descripcion'=>'Molina','provincia_id'=>31],
            ['id'=>174,'descripcion'=>'Rauco','provincia_id'=>31],
            ['id'=>175,'descripcion'=>'Romeral','provincia_id'=>31],
            ['id'=>176,'descripcion'=>'Sagrada Familia','provincia_id'=>31],
            ['id'=>177,'descripcion'=>'Teno','provincia_id'=>31],
            ['id'=>178,'descripcion'=>'Vichuquén','provincia_id'=>31],
            ['id'=>179,'descripcion'=>'Colbún','provincia_id'=>32],
            ['id'=>180,'descripcion'=>'Linares','provincia_id'=>32],
            ['id'=>181,'descripcion'=>'Longaví','provincia_id'=>32],
            ['id'=>182,'descripcion'=>'Parral','provincia_id'=>32],
            ['id'=>183,'descripcion'=>'Retiro','provincia_id'=>32],
            ['id'=>184,'descripcion'=>'San Javier','provincia_id'=>32],
            ['id'=>185,'descripcion'=>'Villa Alegre','provincia_id'=>32],
            ['id'=>186,'descripcion'=>'Yerbas Buenas','provincia_id'=>32],
            ['id'=>187,'descripcion'=>'Constitución','provincia_id'=>33],
            ['id'=>188,'descripcion'=>'Curepto','provincia_id'=>33],
            ['id'=>189,'descripcion'=>'Empedrado','provincia_id'=>33],
            ['id'=>190,'descripcion'=>'Maule','provincia_id'=>33],
            ['id'=>191,'descripcion'=>'Pelarco','provincia_id'=>33],
            ['id'=>192,'descripcion'=>'Pencahue','provincia_id'=>33],
            ['id'=>193,'descripcion'=>'Río Claro','provincia_id'=>33],
            ['id'=>194,'descripcion'=>'San Clemente','provincia_id'=>33],
            ['id'=>195,'descripcion'=>'San Rafael','provincia_id'=>33],
            ['id'=>196,'descripcion'=>'Talca','provincia_id'=>33],
            ['id'=>197,'descripcion'=>'Arauco','provincia_id'=>34],
            ['id'=>198,'descripcion'=>'Cañete','provincia_id'=>34],
            ['id'=>199,'descripcion'=>'Contulmo','provincia_id'=>34],
            ['id'=>200,'descripcion'=>'Curanilahue','provincia_id'=>34],
            ['id'=>201,'descripcion'=>'Lebu','provincia_id'=>34],
            ['id'=>202,'descripcion'=>'Los Álamos','provincia_id'=>34],
            ['id'=>203,'descripcion'=>'Tirúa','provincia_id'=>34],
            ['id'=>204,'descripcion'=>'Alto Biobío','provincia_id'=>35],
            ['id'=>205,'descripcion'=>'Antuco','provincia_id'=>35],
            ['id'=>206,'descripcion'=>'Cabrero','provincia_id'=>35],
            ['id'=>207,'descripcion'=>'Laja','provincia_id'=>35],
            ['id'=>208,'descripcion'=>'Los Ángeles','provincia_id'=>35],
            ['id'=>209,'descripcion'=>'Mulchén','provincia_id'=>35],
            ['id'=>210,'descripcion'=>'Nacimiento','provincia_id'=>35],
            ['id'=>211,'descripcion'=>'Negrete','provincia_id'=>35],
            ['id'=>212,'descripcion'=>'Quilaco','provincia_id'=>35],
            ['id'=>213,'descripcion'=>'Quilleco','provincia_id'=>35],
            ['id'=>214,'descripcion'=>'San Rosendo','provincia_id'=>35],
            ['id'=>215,'descripcion'=>'Santa Bárbara','provincia_id'=>35],
            ['id'=>216,'descripcion'=>'Tucapel','provincia_id'=>35],
            ['id'=>217,'descripcion'=>'Yumbel','provincia_id'=>35],
            ['id'=>218,'descripcion'=>'Chiguayante','provincia_id'=>36],
            ['id'=>219,'descripcion'=>'Concepción','provincia_id'=>36],
            ['id'=>220,'descripcion'=>'Coronel','provincia_id'=>36],
            ['id'=>221,'descripcion'=>'Florida','provincia_id'=>36],
            ['id'=>222,'descripcion'=>'Hualpén','provincia_id'=>36],
            ['id'=>223,'descripcion'=>'Hualqui','provincia_id'=>36],
            ['id'=>224,'descripcion'=>'Lota','provincia_id'=>36],
            ['id'=>225,'descripcion'=>'Penco','provincia_id'=>36],
            ['id'=>226,'descripcion'=>'San Pedro de La Paz','provincia_id'=>36],
            ['id'=>227,'descripcion'=>'Santa Juana','provincia_id'=>36],
            ['id'=>228,'descripcion'=>'Talcahuano','provincia_id'=>36],
            ['id'=>229,'descripcion'=>'Tomé','provincia_id'=>36],
            ['id'=>230,'descripcion'=>'Bulnes','provincia_id'=>37],
            ['id'=>231,'descripcion'=>'Chillán','provincia_id'=>37],
            ['id'=>232,'descripcion'=>'Chillán Viejo','provincia_id'=>37],
            ['id'=>233,'descripcion'=>'Cobquecura','provincia_id'=>37],
            ['id'=>234,'descripcion'=>'Coelemu','provincia_id'=>37],
            ['id'=>235,'descripcion'=>'Coihueco','provincia_id'=>37],
            ['id'=>236,'descripcion'=>'El Carmen','provincia_id'=>37],
            ['id'=>237,'descripcion'=>'Ninhue','provincia_id'=>37],
            ['id'=>238,'descripcion'=>'Ñiquen','provincia_id'=>37],
            ['id'=>239,'descripcion'=>'Pemuco','provincia_id'=>37],
            ['id'=>240,'descripcion'=>'Pinto','provincia_id'=>37],
            ['id'=>241,'descripcion'=>'Portezuelo','provincia_id'=>37],
            ['id'=>242,'descripcion'=>'Quillón','provincia_id'=>37],
            ['id'=>243,'descripcion'=>'Quirihue','provincia_id'=>37],
            ['id'=>244,'descripcion'=>'Ránquil','provincia_id'=>37],
            ['id'=>245,'descripcion'=>'San Carlos','provincia_id'=>37],
            ['id'=>246,'descripcion'=>'San Fabián','provincia_id'=>37],
            ['id'=>247,'descripcion'=>'San Ignacio','provincia_id'=>37],
            ['id'=>248,'descripcion'=>'San Nicolás','provincia_id'=>37],
            ['id'=>249,'descripcion'=>'Treguaco','provincia_id'=>37],
            ['id'=>250,'descripcion'=>'Yungay','provincia_id'=>37],
            ['id'=>251,'descripcion'=>'Carahue','provincia_id'=>38],
            ['id'=>252,'descripcion'=>'Cholchol','provincia_id'=>38],
            ['id'=>253,'descripcion'=>'Cunco','provincia_id'=>38],
            ['id'=>254,'descripcion'=>'Curarrehue','provincia_id'=>38],
            ['id'=>255,'descripcion'=>'Freire','provincia_id'=>38],
            ['id'=>256,'descripcion'=>'Galvarino','provincia_id'=>38],
            ['id'=>257,'descripcion'=>'Gorbea','provincia_id'=>38],
            ['id'=>258,'descripcion'=>'Lautaro','provincia_id'=>38],
            ['id'=>259,'descripcion'=>'Loncoche','provincia_id'=>38],
            ['id'=>260,'descripcion'=>'Melipeuco','provincia_id'=>38],
            ['id'=>261,'descripcion'=>'Nueva Imperial','provincia_id'=>38],
            ['id'=>262,'descripcion'=>'Padre Las Casas','provincia_id'=>38],
            ['id'=>263,'descripcion'=>'Perquenco','provincia_id'=>38],
            ['id'=>264,'descripcion'=>'Pitrufquén','provincia_id'=>38],
            ['id'=>265,'descripcion'=>'Pucón','provincia_id'=>38],
            ['id'=>266,'descripcion'=>'Saavedra','provincia_id'=>38],
            ['id'=>267,'descripcion'=>'Temuco','provincia_id'=>38],
            ['id'=>268,'descripcion'=>'Teodoro Schmidt','provincia_id'=>38],
            ['id'=>269,'descripcion'=>'Toltén','provincia_id'=>38],
            ['id'=>270,'descripcion'=>'Vilcún','provincia_id'=>38],
            ['id'=>271,'descripcion'=>'Villarrica','provincia_id'=>38],
            ['id'=>272,'descripcion'=>'Angol','provincia_id'=>39],
            ['id'=>273,'descripcion'=>'Collipulli','provincia_id'=>39],
            ['id'=>274,'descripcion'=>'Curacautín','provincia_id'=>39],
            ['id'=>275,'descripcion'=>'Ercilla','provincia_id'=>39],
            ['id'=>276,'descripcion'=>'Lonquimay','provincia_id'=>39],
            ['id'=>277,'descripcion'=>'Los Sauces','provincia_id'=>39],
            ['id'=>278,'descripcion'=>'Lumaco','provincia_id'=>39],
            ['id'=>279,'descripcion'=>'Purén','provincia_id'=>39],
            ['id'=>280,'descripcion'=>'Renaico','provincia_id'=>39],
            ['id'=>281,'descripcion'=>'Traiguén','provincia_id'=>39],
            ['id'=>282,'descripcion'=>'Victoria','provincia_id'=>39],
            ['id'=>283,'descripcion'=>'Corral','provincia_id'=>40],
            ['id'=>284,'descripcion'=>'Lanco','provincia_id'=>40],
            ['id'=>285,'descripcion'=>'Los Lagos','provincia_id'=>40],
            ['id'=>286,'descripcion'=>'Máfil','provincia_id'=>40],
            ['id'=>287,'descripcion'=>'Mariquina','provincia_id'=>40],
            ['id'=>288,'descripcion'=>'Paillaco','provincia_id'=>40],
            ['id'=>289,'descripcion'=>'Panguipulli','provincia_id'=>40],
            ['id'=>290,'descripcion'=>'Valdivia','provincia_id'=>40],
            ['id'=>291,'descripcion'=>'Futrono','provincia_id'=>41],
            ['id'=>292,'descripcion'=>'La Unión','provincia_id'=>41],
            ['id'=>293,'descripcion'=>'Lago Ranco','provincia_id'=>41],
            ['id'=>294,'descripcion'=>'Río Bueno','provincia_id'=>41],
            ['id'=>295,'descripcion'=>'Ancud','provincia_id'=>42],
            ['id'=>296,'descripcion'=>'Castro','provincia_id'=>42],
            ['id'=>297,'descripcion'=>'Chonchi','provincia_id'=>42],
            ['id'=>298,'descripcion'=>'Curaco de Vélez','provincia_id'=>42],
            ['id'=>299,'descripcion'=>'Dalcahue','provincia_id'=>42],
            ['id'=>300,'descripcion'=>'Puqueldón','provincia_id'=>42],
            ['id'=>301,'descripcion'=>'Queilén','provincia_id'=>42],
            ['id'=>302,'descripcion'=>'Quemchi','provincia_id'=>42],
            ['id'=>303,'descripcion'=>'Quellón','provincia_id'=>42],
            ['id'=>304,'descripcion'=>'Quinchao','provincia_id'=>42],
            ['id'=>305,'descripcion'=>'Calbuco','provincia_id'=>43],
            ['id'=>306,'descripcion'=>'Cochamó','provincia_id'=>43],
            ['id'=>307,'descripcion'=>'Fresia','provincia_id'=>43],
            ['id'=>308,'descripcion'=>'Frutillar','provincia_id'=>43],
            ['id'=>309,'descripcion'=>'Llanquihue','provincia_id'=>43],
            ['id'=>310,'descripcion'=>'Los Muermos','provincia_id'=>43],
            ['id'=>311,'descripcion'=>'Maullín','provincia_id'=>43],
            ['id'=>312,'descripcion'=>'Puerto Montt','provincia_id'=>43],
            ['id'=>313,'descripcion'=>'Puerto Varas','provincia_id'=>43],
            ['id'=>314,'descripcion'=>'Osorno','provincia_id'=>44],
            ['id'=>315,'descripcion'=>'Puero Octay','provincia_id'=>44],
            ['id'=>316,'descripcion'=>'Purranque','provincia_id'=>44],
            ['id'=>317,'descripcion'=>'Puyehue','provincia_id'=>44],
            ['id'=>318,'descripcion'=>'Río Negro','provincia_id'=>44],
            ['id'=>319,'descripcion'=>'San Juan de la Costa','provincia_id'=>44],
            ['id'=>320,'descripcion'=>'San Pablo','provincia_id'=>44],
            ['id'=>321,'descripcion'=>'Chaitén','provincia_id'=>45],
            ['id'=>322,'descripcion'=>'Futaleufú','provincia_id'=>45],
            ['id'=>323,'descripcion'=>'Hualaihué','provincia_id'=>45],
            ['id'=>324,'descripcion'=>'Palena','provincia_id'=>45],
            ['id'=>325,'descripcion'=>'Aisén','provincia_id'=>46],
            ['id'=>326,'descripcion'=>'Cisnes','provincia_id'=>46],
            ['id'=>327,'descripcion'=>'Guaitecas','provincia_id'=>46],
            ['id'=>328,'descripcion'=>'Cochrane','provincia_id'=>47],
            ['id'=>329,'descripcion'=>'O\'higgins','provincia_id'=>47],
            ['id'=>330,'descripcion'=>'Tortel','provincia_id'=>47],
            ['id'=>331,'descripcion'=>'Coihaique','provincia_id'=>48],
            ['id'=>332,'descripcion'=>'Lago Verde','provincia_id'=>48],
            ['id'=>333,'descripcion'=>'Chile Chico','provincia_id'=>49],
            ['id'=>334,'descripcion'=>'Río Ibáñez','provincia_id'=>49],
            ['id'=>335,'descripcion'=>'Antártica','provincia_id'=>50],
            ['id'=>336,'descripcion'=>'Cabo de Hornos','provincia_id'=>50],
            ['id'=>337,'descripcion'=>'Laguna Blanca','provincia_id'=>51],
            ['id'=>338,'descripcion'=>'Punta Arenas','provincia_id'=>51],
            ['id'=>339,'descripcion'=>'Río Verde','provincia_id'=>51],
            ['id'=>340,'descripcion'=>'San Gregorio','provincia_id'=>51],
            ['id'=>341,'descripcion'=>'Porvenir','provincia_id'=>52],
            ['id'=>342,'descripcion'=>'Primavera','provincia_id'=>52],
            ['id'=>343,'descripcion'=>'Timaukel','provincia_id'=>52],
            ['id'=>344,'descripcion'=>'Natales','provincia_id'=>53],
            ['id'=>345,'descripcion'=>'Torres del Paine','provincia_id'=>53]
        ]);
    }

}
